bus_sys_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BusSysUserBundle:Default:index }
    
check_add_data_to_bus_table:
    pattern:  /check/bus/adddata
    defaults: { _controller: BusSysUserBundle:DBconnect:bus }
    
check_add_data_to_passenger_table:
    pattern:  /check/passenger/adddata
    defaults: { _controller: BusSysUserBundle:DBconnect:passenger }

check_add_data_to_purchased_table:
    pattern:  /check/purchased/adddata
    defaults: { _controller: BusSysUserBundle:DBconnect:purchased }
    
check_bus_count:
    pattern:  /check/busCount
    defaults: { _controller: BusSysUserBundle:DBconnect:busCount }
    
check_bus_smoking_count:
    pattern:  /check/busSmokingCount
    defaults: { _controller: BusSysUserBundle:DBconnect:busSmoking }
    
check_validate_user:
    pattern:  /check/validateUser
    defaults: { _controller: BusSysUserBundle:DBconnect:validate }