parameters:
#    bus_sys_user.example.class: BusSys\UserBundle\Example

services:
#    bus_sys_user.example:
#        class: %bus_sys_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
