parameters:
#    kam_bus_sys_style.example.class: KamBusSys\StyleBundle\Example

services:
#    kam_bus_sys_style.example:
#        class: %kam_bus_sys_style.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
