_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }
    
__test:
    pattern:  /hello
    defaults: { _controller: AcmeDemoBundle:Welcome:hello }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo